### ISSUE TITLE
Страница Регистрации - Неверный Placeholder поля Username

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/Registration-Authorization#101]
Ожидаемый результат: Username
Фактический результат: username

![Screenshot_20220112-181231_1](https://user-images.githubusercontent.com/95171672/149213483-ad288bb2-349b-4efb-b6bf-aec22f403be5.jpg)

Шаги по нахождению бага:
1) Перейти в тестовую среду по ссылке https://sandbox.qax-camp.com.ua/
2) Найти поле "Username"
3) Обратить внимание на Placeholder

**Comment by scholokov** [comment]
1.
очередность:
шаги
ожидаемый-фактический результат
скрин

**Comment by scholokov** [comment]
2.
Найти поле "Username"
Обратить внимание на Placeholder

можно и так, а можно и объединить в одну строку

**Comment by scholokov** [comment]
3.
Перейти в тестовую среду по ссылке https://sandbox.qax-camp.com.ua/

слово "по ссылке" тут лишнее
а можно вообще писать:
Открыть  https://sandbox.qax-camp.com.ua/

**Comment by scholokov** [comment]
4. лучше писать:

Ожидаемый результат: 
Username

Фактический результат: 
username

вместо:
Ожидаемый результат: Username
Фактический результат: username

в этом случае проще понять что длинее, и в чем разница

**Comment by scholokov** [comment]
5.
а самый красивый вариант вместо:
Перейти в тестовую среду по ссылке https://sandbox.qax-camp.com.ua/

Открыть страницу регистрации (https://sandbox.qax-camp.com.ua/login)
потому что, как ты видел, если ты заранее авторизировался, то ты попадешь просто на страницу курсов, а не страницу регистрации
