### ISSUE TITLE
Registration page - username - invalid username field id

### ISSUE THREAD

**Issue by Konushevskyi** [scholokov/Registration-Authorization#19]
**Precondition**
Open registration page https://sandbox.qax-camp.com.ua/user/usertester/

**Description**
invalid username field id

**Steps to reproduce**
1. Open dev. tools
2. Inspect username field
3. Сompare field id with requirements

**Act. result**
id **"user_login-533"**

**Exp. result**
id **"Username"**

**Environment**
Desktop/W10/Google Chrome 93.0.4577.82 (64 bit)

**Attachments**
![Screenshot_2](https://user-images.githubusercontent.com/89162949/133893583-1faf90f9-396c-464c-bd3b-29a4857fb6c4.png)

**Comment by scholokov** [comment]
id - не проверяем
в таблице указано для удобства
